{
    'name': "Website Dating (Super Alpha)",
    'version': "0.1.5",
    'author': "Sythil",
    'category': "Tools",
    'summary': "A directory of single people",
    'license':'GPL-3',
    'data': [
    'res_dating.xml',
    'res_partner.xml',
    'views/website_dating_views.xml',
    'ir.cron.csv',
    'res.dating.fake.first.csv',
    'res.dating.fake.last.csv',
    'res.partner.gender.csv',
    'website.menu.csv',
    'res.partner.relationship.csv',
    ],
    'demo': [],
    'depends': ['crm','base_location_geonames_import','partner_firstname', 'website'],
    'installable': True,
}