{
    'name': "Entity SMS",
    'version': "2.6",
    'author': "Sythil",
    'category': "Tools",
    'summary': "Allows 2 way sms conversations between leads/partners using the twilio gateway",
    'data': [
        'ir.cron.csv',
        'esms_core.xml',
        'res_partner.xml',
        'esms_accounts.xml',
        'esms_templates.xml',
        'esms_import.xml',
        'esms_compose.xml',
        'esms_compose_multi.xml',
        'esms_autoresponse.xml',
        'esms_history.xml',
        'esms.gateways.csv',
        'ir.actions.server.csv',
        'base.action.rule.csv',
	'security/ir.model.access.csv',
	'res.country.csv',
	'smsgateway/gateway_config.xml',
        'smsglobal/gateway_config.xml',
        'twilio/gateway_config.xml',
    ],
    'demo': [],
    'depends': ['web', 'crm'],
    'installable': True,
}