{
    'name': "Entity SMS V2 (Multi Gateway)",
    'version': "1.4",
    'author': "Sythil",
    'category': "Tools",
    'summary': "Allows you send smses from any model",
    'data': [
        'views/qweb.xml',
        'esms.xml',
        'esms.gateways.csv',
	'security/ir.model.access.csv',
        'esms_templates.xml',
        'smsgateway/gateway_config.xml',
        'smsglobal/gateway_config.xml',
        'twilio/gateway_config.xml',
    ],
    'qweb': ['static/src/xml/esms_widget.xml'],
    'demo': [],
    'depends': ['web', 'crm'],
    'installable': True,
}